motocart.isSidewalkRight();
motocart.isSidewalkAhead();
motocart.isAtStop ();
motocart.canRightTurn ();
motocart.canLeftTurn ();
motocart.canGoStraight (1);
motocart.summonCart();
motocart.move(1);
motocart.rotate(0);
motocart.position();
motocart.heading();